"""PDF report generation using ReportLab."""
import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from core.config import settings

BRAND_GREEN = colors.HexColor("#2e7d32")
PAGE_WIDTH, PAGE_HEIGHT = letter


def _level_color(risk_level: str):
    return colors.HexColor(settings.RISK_COLORS.get(risk_level, "#616161"))


def _draw_header(c):
    c.setFillColor(BRAND_GREEN)
    c.rect(0, PAGE_HEIGHT - 1.1 * inch, PAGE_WIDTH, 1.1 * inch, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(0.6 * inch, PAGE_HEIGHT - 0.6 * inch, settings.APP_NAME)
    c.setFont("Helvetica", 10)
    c.drawString(0.6 * inch, PAGE_HEIGHT - 0.85 * inch,
                 "Protecting Kenya's Food Security, Ensuring Future Sustainability.")


def _draw_footer(c):
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.grey)
    c.drawString(0.6 * inch, 0.4 * inch,
                 f"Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} | AgriShield")


def build(county_name: str, prediction: dict, report_type: str,
          detailed: bool) -> io.BytesIO:
    """Build a branded PDF report and return it as a byte stream."""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)

    _draw_header(c)
    _draw_footer(c)

    # Title block
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(0.6 * inch, PAGE_HEIGHT - 1.6 * inch,
                 f"Agricultural Risk Report: {county_name}")

    c.setFont("Helvetica", 11)
    c.drawString(0.6 * inch, PAGE_HEIGHT - 1.9 * inch,
                 f"Report type: {report_type.capitalize()}")
    c.drawString(0.6 * inch, PAGE_HEIGHT - 2.15 * inch,
                 f"Date: {datetime.utcnow().strftime('%Y-%m-%d')}")

    # Risk score panel
    risk_score = prediction.get("risk_score", 0.0)
    risk_level = prediction.get("risk_level", "SAFE")

    panel_y = PAGE_HEIGHT - 3.4 * inch
    c.setFillColor(colors.HexColor("#f5f5f5"))
    c.roundRect(0.6 * inch, panel_y, PAGE_WIDTH - 1.2 * inch, 1.0 * inch,
                8, fill=1, stroke=0)

    c.setFillColor(_level_color(risk_level))
    c.setFont("Helvetica-Bold", 26)
    c.drawString(0.9 * inch, panel_y + 0.45 * inch, f"{risk_score}%")

    c.setFont("Helvetica-Bold", 14)
    c.drawString(2.2 * inch, panel_y + 0.5 * inch, risk_level)

    # Gauge bar
    bar_x = 0.9 * inch
    bar_y = panel_y + 0.15 * inch
    bar_width = PAGE_WIDTH - 1.8 * inch
    c.setFillColor(colors.HexColor("#e0e0e0"))
    c.rect(bar_x, bar_y, bar_width, 0.12 * inch, fill=1, stroke=0)
    c.setFillColor(_level_color(risk_level))
    c.rect(bar_x, bar_y, bar_width * (risk_score / 100), 0.12 * inch,
           fill=1, stroke=0)

    # Details
    text_y = panel_y - 0.5 * inch
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.6 * inch, text_y, "Key Findings")

    c.setFont("Helvetica", 11)
    text_y -= 0.3 * inch
    c.drawString(0.6 * inch, text_y,
                 f"Main driver: {prediction.get('main_driver', 'N/A')}")
    text_y -= 0.25 * inch

    # Recommendation (wrapped manually)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.6 * inch, text_y, "Recommendation")
    c.setFont("Helvetica", 11)

    recommendation = prediction.get("recommendation", "")
    words = recommendation.split()
    line = ""
    text_y -= 0.3 * inch
    for word in words:
        if len(line + word) > 80:
            c.drawString(0.6 * inch, text_y, line.strip())
            text_y -= 0.22 * inch
            line = word + " "
        else:
            line += word + " "
    if line:
        c.drawString(0.6 * inch, text_y, line.strip())

    if detailed:
        text_y -= 0.5 * inch
        c.setFont("Helvetica-Bold", 12)
        c.drawString(0.6 * inch, text_y, "Methodology")
        c.setFont("Helvetica", 10)
        text_y -= 0.25 * inch
        methodology = (
            "This report was generated by the AgriShield champion model "
            "(agri-pred-v1) using rainfall anomaly, pasture greenness (NDVI), "
            "temperature, and soil moisture indicators, interpreted by the "
            "Gria Agentic AI assistant."
        )
        for chunk_start in range(0, len(methodology), 80):
            c.drawString(0.6 * inch, text_y, methodology[chunk_start:chunk_start + 80])
            text_y -= 0.2 * inch

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer